backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Articoli Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data Pubblicazione", name: "date", widget: "datetime" }
      - { label: "Estratto / Sintesi", name: "description", widget: "text" }
      - { label: "Testo Articolo", name: "body", widget: "markdown" }
